version: '3'
services:
  front-end:
    build: ./
    image: halosan/dev-machine-frontend:latest
    ports:
     - "3001:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: frontend
