version: '3'
services:
  front-end:
    build: ./
    image: halosan/dev-machine-frontend:latest
    ports:
     - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
     - NODE_ENDPOINT=http://localhost:3000
     - NODE_ENV_IMAGE=halosan/ansible-auto:local
    container_name: frontend
